/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as BSlugRouteImport } from './routes/b/$slug'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as BSlugEditRouteImport } from './routes/b/$slug_.edit'
import { Route as BSlugPlayRouteImport } from './routes/b/$slug_.play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugEditRoute = BSlugEditRouteImport.update({
  id: '/b/$slug_/edit',
  path: '/b/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugPlayRoute = BSlugPlayRouteImport.update({
  id: '/b/$slug_/play',
  path: '/b/$slug/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/signup': typeof SignupRoute
  '/b/$slug': typeof BSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/b/$slug/edit': typeof BSlugEditRoute
  '/b/$slug/play': typeof BSlugPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/signup': typeof SignupRoute
  '/b/$slug': typeof BSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/b/$slug/edit': typeof BSlugEditRoute
  '/b/$slug/play': typeof BSlugPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/signup': typeof SignupRoute
  '/b/$slug': typeof BSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/b/$slug_/edit': typeof BSlugEditRoute
  '/b/$slug_/play': typeof BSlugPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/new'
    | '/signup'
    | '/b/$slug'
    | '/u/$username'
    | '/b/$slug/edit'
    | '/b/$slug/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/new'
    | '/signup'
    | '/b/$slug'
    | '/u/$username'
    | '/b/$slug/edit'
    | '/b/$slug/play'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/new'
    | '/signup'
    | '/b/$slug'
    | '/u/$username'
    | '/b/$slug_/edit'
    | '/b/$slug_/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  SignupRoute: typeof SignupRoute
  BSlugRoute: typeof BSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  BSlugEditRoute: typeof BSlugEditRoute
  BSlugPlayRoute: typeof BSlugPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug_/edit': {
      id: '/b/$slug_/edit'
      path: '/b/$slug/edit'
      fullPath: '/b/$slug/edit'
      preLoaderRoute: typeof BSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug_/play': {
      id: '/b/$slug_/play'
      path: '/b/$slug/play'
      fullPath: '/b/$slug/play'
      preLoaderRoute: typeof BSlugPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  SignupRoute: SignupRoute,
  BSlugRoute: BSlugRoute,
  UUsernameRoute: UUsernameRoute,
  BSlugEditRoute: BSlugEditRoute,
  BSlugPlayRoute: BSlugPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
