// Official French client names (from Blizzard's French patch notes where available).
// [name, short badge label]. Upgrade levels are generated from LEVEL_NAMES_FR.

export const ACTION_NAMES_FR: Record<string, [string, string]> = {
  // Terran units
  scv: ["VCS", "VCS"],
  marine: ["Marine", "Mrn"],
  reaper: ["Faucheur", "Fau"],
  marauder: ["Maraudeur", "Mrd"],
  ghost: ["Fantôme", "Fan"],
  hellion: ["Tourmenteur", "Trm"],
  hellbat: ["Nettoyeur", "Net"],
  "widow-mine": ["Mine veuve", "MV"],
  cyclone: ["Cyclone", "Cyc"],
  "siege-tank": ["Char de siège", "Char"],
  thor: ["Thor", "Thor"],
  viking: ["Viking", "Vik"],
  medivac: ["Médivac", "Méd"],
  liberator: ["Croiseur", "Cro"],
  raven: ["Corbeau", "Crb"],
  banshee: ["Banshee", "Bsh"],
  battlecruiser: ["Cuirassé", "Cui"],
  // Terran buildings
  "command-center": ["Centre de commandement", "CC"],
  "orbital-command": ["Station orbitale", "SO"],
  "planetary-fortress": ["Forteresse planétaire", "FP"],
  "supply-depot": ["Dépôt de ravitaillement", "Dpt"],
  refinery: ["Raffinerie", "Raf"],
  barracks: ["Caserne", "Cas"],
  "engineering-bay": ["Centre technique", "CT"],
  bunker: ["Bunker", "Bnkr"],
  "missile-turret": ["Tourelle lance-missiles", "Tour"],
  "sensor-tower": ["Tour de détection", "TdD"],
  factory: ["Usine", "Usi"],
  "ghost-academy": ["Académie fantôme", "AF"],
  armory: ["Armurerie", "Arm"],
  starport: ["Spatioport", "Spa"],
  "fusion-core": ["Noyau de fusion", "NF"],
  "tech-lab": ["Laboratoire technique", "Lab"],
  reactor: ["Réacteur", "Réa"],
  // Terran upgrades
  stimpack: ["Stimulants", "Stim"],
  "combat-shield": ["Bouclier de combat", "BdC"],
  "concussive-shells": ["Obus incapacitants", "Obus"],
  "infernal-pre-igniter": ["Amorce infernale", "Amo"],
  "drilling-claws": ["Griffes de forage", "Grf"],
  "smart-servos": ["Servoaccélérateurs", "Srvo"],
  "hyperflight-rotors": ["Hyperpropulsion", "Hyp"],
  "cloaking-field": ["Champ de camouflage", "Cam"],
  "advanced-ballistics": ["Balistique avancée", "Bal"],
  "personal-cloaking": ["Camouflage personnel", "CaP"],
  "hisec-auto-tracking": ["Poursuite automatique haute sécurité", "PAHS"],
  "neosteel-armor": ["Armure en NéoAcier", "Néo"],
  "weapon-refit": ["Canon Yamato", "Yam"],
  // Terran abilities
  mule: ["MULE", "MULE"],
  scan: ["Scan", "Scan"],
  "lift-off": ["Décoller", "Déc"],

  // Protoss units
  probe: ["Sonde", "Snd"],
  zealot: ["Zélote", "Zél"],
  stalker: ["Traqueur", "Trq"],
  sentry: ["Sentinelle", "Snt"],
  adept: ["Adepte", "Adp"],
  "high-templar": ["Haut templier", "HT"],
  "dark-templar": ["Templier noir", "TN"],
  archon: ["Archonte", "Arch"],
  observer: ["Observateur", "Obs"],
  "warp-prism": ["Prisme de transfert", "PdT"],
  immortal: ["Immortel", "Imm"],
  colossus: ["Colosse", "Col"],
  disruptor: ["Disrupteur", "Dsr"],
  phoenix: ["Phénix", "Phx"],
  oracle: ["Oracle", "Orc"],
  "void-ray": ["Rayon du Vide", "RdV"],
  tempest: ["Tempête", "Tmp"],
  carrier: ["Porte-nefs", "PN"],
  mothership: ["Vaisseau mère", "VM"],
  // Protoss buildings
  nexus: ["Nexus", "Nex"],
  pylon: ["Pylône", "Pyl"],
  assimilator: ["Assimilateur", "Ass"],
  gateway: ["Portail", "Port"],
  forge: ["Forge", "Frg"],
  "cybernetics-core": ["Noyau cybernétique", "Noy"],
  "photon-cannon": ["Canon à photons", "Can"],
  "shield-battery": ["Batterie de boucliers", "Bat"],
  "twilight-council": ["Conseil crépusculaire", "CC"],
  "robotics-facility": ["Complexe robotique", "Robo"],
  stargate: ["Porte des étoiles", "PdE"],
  "templar-archives": ["Archives templières", "AT"],
  "dark-shrine": ["Sanctuaire noir", "SN"],
  "robotics-bay": ["Baie robotique", "BR"],
  "fleet-beacon": ["Balise de la flotte", "BdF"],
  // Protoss upgrades
  "warp-gate": ["Porte de transfert", "PT"],
  charge: ["Charge", "Chg"],
  blink: ["Transfert", "Trf"],
  "resonating-glaives": ["Glaives de résonance", "Glv"],
  "psionic-storm": ["Tempête psionique", "TP"],
  "shadow-stride": ["Brèche d'ombre", "Brè"],
  "extended-thermal-lance": ["Thermolance", "Thm"],
  "gravitic-boosters": ["Réacteurs antigrav", "RAg"],
  "gravitic-drive": ["Propulsion gravitique", "PG"],
  "anion-pulse-crystals": ["Cristaux à impulsions anioniques", "CIA"],
  "flux-vanes": ["Aubes de flux", "Aub"],
  // Protoss abilities
  "chrono-boost": ["Poussée temporelle", "Chr"],

  // Zerg units
  drone: ["Drone", "Drn"],
  overlord: ["Dominant", "Dom"],
  queen: ["Reine", "Rne"],
  zergling: ["Zergling", "Ling"],
  baneling: ["Chancre", "Chc"],
  roach: ["Cafard", "Caf"],
  ravager: ["Saccageur", "Sac"],
  overseer: ["Vigilant", "Vig"],
  hydralisk: ["Hydralisk", "Hyd"],
  lurker: ["Rôdeur", "Rôd"],
  infestor: ["Infestateur", "Inf"],
  "swarm-host": ["Essaimeur", "Ess"],
  mutalisk: ["Mutalisk", "Muta"],
  corruptor: ["Corrupteur", "Cor"],
  "brood-lord": ["Seigneur-vermine", "SV"],
  viper: ["Vipère", "Vip"],
  ultralisk: ["Ultralisk", "Ult"],
  // Zerg buildings
  hatchery: ["Couveuse", "Couv"],
  extractor: ["Extracteur", "Ext"],
  "spawning-pool": ["Bassin génétique", "BG"],
  "evolution-chamber": ["Chambre d'évolution", "Évo"],
  "roach-warren": ["Terrier de cafards", "TdC"],
  "baneling-nest": ["Nid de chancres", "NdC"],
  "spine-crawler": ["Aiguillon rampant", "Aig"],
  "spore-crawler": ["Sporuleur rampant", "Spo"],
  lair: ["Terrier", "Ter"],
  "hydralisk-den": ["Tanière d'hydralisks", "TdH"],
  "lurker-den": ["Terrier de rôdeurs", "TdR"],
  "infestation-pit": ["Fosse d'infestation", "Fos"],
  spire: ["Flèche", "Flè"],
  "nydus-network": ["Réseau de Nydus", "Nyd"],
  hive: ["Ruche", "Ruch"],
  "ultralisk-cavern": ["Caverne d'ultralisks", "CdU"],
  "greater-spire": ["Grande flèche", "GF"],
  // Zerg upgrades
  "metabolic-boost": ["Boost métabolique", "Bst"],
  "adrenal-glands": ["Glandes surrénales", "Glan"],
  "centrifugal-hooks": ["Crochets centrifuges", "Cro"],
  "glial-reconstitution": ["Reconstitution gliale", "Gli"],
  "tunneling-claws": ["Griffes fouisseuses", "Grf"],
  burrow: ["Enfouir", "Enf"],
  "muscular-augments": ["Implants musculaires", "Imp"],
  "grooved-spines": ["Aiguillons fuselés", "Fus"],
  "pneumatized-carapace": ["Carapace pneumatique", "Pneu"],
  "neural-parasite": ["Parasite neural", "Par"],
  "chitinous-plating": ["Armure chitineuse", "Chi"],
  "anabolic-synthesis": ["Synthèse anabolique", "Ana"],
  // Zerg abilities
  "inject-larva": ["Injection de larves", "Inj"],
  "spread-creep": ["Tumeur muqueuse", "Tum"],
};

/** French names for the three-level weapon/armor upgrade families: [name, short prefix]. */
export const LEVEL_NAMES_FR: Record<string, [string, string]> = {
  "infantry-weapons": ["Armes d'infanterie", "AI"],
  "infantry-armor": ["Blindage d'infanterie", "BI"],
  "vehicle-weapons": ["Armes de véhicules", "AV"],
  "ship-weapons": ["Armes de vaisseaux", "AVs"],
  "vehicle-ship-plating": ["Blindage de véhicules et de vaisseaux", "BV"],
  "ground-weapons": ["Armes terrestres", "AT"],
  "ground-armor": ["Armures terrestres", "ArT"],
  shields: ["Boucliers", "Bcl"],
  "air-weapons": ["Armes aériennes", "AA"],
  "air-armor": ["Armures aériennes", "ArA"],
  "melee-attacks": ["Attaques de mêlée", "AM"],
  "missile-attacks": ["Attaques à projectiles", "AP"],
  "ground-carapace": ["Carapace terrestre", "CT"],
  "flyer-attacks": ["Attaques aériennes", "AAé"],
  "flyer-carapace": ["Carapace aérienne", "CA"],
};
